### ISSUE TITLE
Make menu look more like minecraft ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-web-client#113]
The current menu looks pretty nice, but I wonder if people have a clue what it is about if first coming there.
Maybe we can put the prismarine logo, the green color ?

Maybe some short explanation on what this is ?

**Comment by Karang** [comment]
We could render a cube map of the terrain with pviewer using https://threejs.org/docs/#api/en/cameras/CubeCamera so we could use it as a rotating background for the menu like vanilla minecraft.

And since the minecraft title screen seed has been found it could be made almost identical https://www.pcgamer.com/minecraft-title-screen-seed/

I think it would be funny.

**Comment by Karang** [comment]
Here is the render of the original title screen scene in pviewer https://github.com/PrismarineJS/prismarine-web-client/blob/master/assets/title.jpg

Generated using https://github.com/spite/THREE.CubemapToEquirectangular

And here is how to use it: https://threejs.org/examples/webgl_panorama_equirectangular.html

**Comment by rom1504** [comment]
done, thanks @Karang
